+ MODEL_NAME=yiyic/mt5_me5_atlatic_fami_32_2layers_corrector
++ pwd
+ wd=/home/cs.aau.dk/ng78zb/vec2text_exp
+ echo 'working directory /home/cs.aau.dk/ng78zb/vec2text_exp'
+ export HF_HOME=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache
+ HF_HOME=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache
+ export HF_DATASETS_CACHE=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache/datasets
+ HF_DATASETS_CACHE=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache/datasets
+ export DATASET_CACHE_PATH=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache
+ DATASET_CACHE_PATH=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache
+ export WANDB_CACHE_DIR=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache/wandb/artifcats/
+ WANDB_CACHE_DIR=/home/cs.aau.dk/ng78zb/vec2text_exp/.cache/wandb/artifcats/
+ export NCCL_P2P_LEVEL=NVL
+ NCCL_P2P_LEVEL=NVL
+ export NCCL_IB_DISABLE=1
+ NCCL_IB_DISABLE=1
+ export TORCH_NCCL_ENABLE_MONITORING=0
+ TORCH_NCCL_ENABLE_MONITORING=0
+ export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
+ TORCH_NCCL_ASYNC_ERROR_HANDLING=1
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ SIF=/home/cs.aau.dk/ng78zb/pytorch_23.10-py3.sif
+ echo 'sif /home/cs.aau.dk/ng78zb/pytorch_23.10-py3.sif'
+ echo 'launch evaluation yiyic/mt5_me5_atlatic_fami_32_2layers_corrector'
+ srun singularity exec --nv --cleanenv --bind /home/cs.aau.dk/ng78zb/vec2text_exp:/home/cs.aau.dk/ng78zb/vec2text_exp /home/cs.aau.dk/ng78zb/pytorch_23.10-py3.sif python -m evaluation yiyic/mt5_me5_atlatic_fami_32_2layers_corrector
13:4: not a valid test operator: (
13:4: not a valid test operator: 535.183.01
/home/cs.aau.dk/ng78zb/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cs.aau.dk/ng78zb/vec2text_exp/evaluation.py", line 103, in <module>
    plac.call(eval_one_model)
  File "/home/cs.aau.dk/ng78zb/.local/lib/python3.10/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/home/cs.aau.dk/ng78zb/.local/lib/python3.10/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/cs.aau.dk/ng78zb/vec2text_exp/evaluation.py", line 57, in eval_one_model
    experiment, trainer = analyze_utils.load_experiment_and_trainer_from_pretrained(model_name, use_less_data=3000)
  File "/home/cs.aau.dk/ng78zb/vec2text_exp/vec2text/analyze_utils.py", line 168, in load_experiment_and_trainer_from_pretrained
    trainer = experiment.load_trainer()
  File "/home/cs.aau.dk/ng78zb/vec2text_exp/vec2text/experiments.py", line 806, in load_trainer
    ) = vec2text.aliases.load_experiment_and_trainer_from_alias(
  File "/home/cs.aau.dk/ng78zb/vec2text_exp/vec2text/aliases.py", line 146, in load_experiment_and_trainer_from_alias
    experiment, trainer = vec2text.analyze_utils.load_experiment_and_trainer(
  File "/home/cs.aau.dk/ng78zb/vec2text_exp/vec2text/analyze_utils.py", line 38, in load_experiment_and_trainer
    checkpoint = get_last_checkpoint(checkpoint_folder)  # a checkpoint
  File "/home/cs.aau.dk/ng78zb/.local/lib/python3.10/site-packages/transformers/trainer_utils.py", line 207, in get_last_checkpoint
    content = os.listdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/project_465000909/whitening/vec2text_exp/saves/inverters/mt5_multilingual_e5_base_mt-ms_atl_fami_32_2layers_prefix'
[2024-07-07 10:30:49,609] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2024-07-07 10:30:49,609] torch._dynamo.utils: [INFO] Function    Runtimes (s)
[2024-07-07 10:30:49,609] torch._dynamo.utils: [INFO] ----------  --------------
srun: error: a768-l40-02: task 0: Exited with exit code 1
